
services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile.dev
    volumes:
      - ./backend:/var/www/html/
    ports:
      - "3000:3000"
    command: >
      sh -c "
      npm install &&
      npm start
      "
    networks:
      - default


  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taskmaster
    ports:
      - "5432:5432"
    networks:
      - default

networks:
  default:
    driver: bridge