
services:

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taskmaster
    ports:
      - "3306:3306"
    networks:
      - default
    volumes:
      - ./backend/mysql_data:/var/lib/mysql
      
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile.dev
    volumes:
      - ./backend:/var/www/html/backend
      - /var/www/html/backend/node_modules
    ports:
      - "3000:3000"
    command: >
      sh -c "
      npm install &&
      npx prisma generate &&
      npm start
      "
    networks:
      - default
    depends_on:
      - db

networks:
  default:
    driver: bridge